version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: ciom
      POSTGRES_PASSWORD: Nachoc04042017@
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Usa un correo válido aquí
      PGADMIN_DEFAULT_PASSWORD: Nachoc04042017@
    ports:
      - "8081:80"  # Cambia el puerto si está ocupado
    networks:
      - pg-network
    depends_on:
      - postgres

networks:
  pg-network:
    driver: bridge

volumes:
  postgres-data:
