# Usar la imagen oficial de Ubuntu
FROM ubuntu

# Instalar el servidor SSH y curl
RUN apt update && apt install -y openssh-server curl sudo

# Crear los directorios necesarios
RUN mkdir /var/run/sshd

# Establecer una contraseña para el usuario root
RUN echo 'root:yourpassword' | chpasswd

# Permitir el acceso SSH del usuario root
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Exponer los puertos 22 (SSH), 80, y 8080
EXPOSE 22 80 8080

# Crear volumen para persistir información
VOLUME /data

# Ejecutar el comando para instalar CasaOS
RUN curl -fsSL https://get.casaos.io | sudo bash

# Iniciar el servidor SSH
CMD ["/usr/sbin/sshd", "-D"]
