version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: YOUR_DAtABASE
      MYSQL_USER: YOUR_USER
      MYSQL_PASSWORD: YOUR_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: YOUR_USER
      PMA_PASSWORD: YOUR_PASSWORD
    ports:
      - "8080:80"
    networks:
      - db_network

volumes:
  mysql_data:

networks:
  db_network:
    driver: bridge
