# Usar la imagen oficial de Ubuntu
FROM ubuntu

# Instalar el servidor SSH
RUN apt update && apt install -y openssh-server

# Crear los directorios necesarios
RUN mkdir /var/run/sshd

# Establecer una contraseña para el usuario root
RUN echo 'root:yourpassword' | chpasswd

# Permitir el acceso SSH del usuario root
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Exponer el puerto 22 para SSH
EXPOSE 22

# Iniciar el servidor SSH
CMD ["/usr/sbin/sshd", "-D"]
